### ISSUE TITLE
installation issue: Cant find "_SoapySDR"

### ISSUE THREAD

**Issue by mkbehbeh** [myriadrf/pyLMS7002Soapy#2]
after installing the pyLMS7002Soapy module, I followed the directions and installed the module.  The install script completed without errors and I can use the LimeSDRmini in GQRX, PathosFlow and GNURadio so that part of PathosSDRis working.  However, when i ran the simple test to import pyLMS7002Soapy it fails with the following traceback.  
I have followed the path in the error message and the files exist 
"_soapySDR.pyd" is located in "C:\Program Files\PothosSDR\lib\python2.7\site-packages" 
C:\Program Files\PothosSDR\lib\python2.7\site-packages is in both $PATH and $PythonPath

>>> from pyLMS7002Soapy import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pyLMS7002Soapy\__init__.py", line 2, in <module>
    from pyLMS7002Soapy import *
  File "C:\Python27\lib\site-packages\pyLMS7002Soapy\pyLMS7002Soapy.py", line 1, in <module>
    import SoapySDR
  File "C:\Program Files\PothosSDR\lib\python2.7\site-packages\SoapySDR.py", line 17, in <module>
    _SoapySDR = swig_import_helper()
  File "C:\Program Files\PothosSDR\lib\python2.7\site-packages\SoapySDR.py", line 16, in swig_import_helper
    return importlib.import_module('_SoapySDR')
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: DLL load failed: The specified module could not be found.

It seems to be some kind of path issue with not finding the file, but I cant figure out where.  What am I missing?

**Comment by mkbehbeh** [comment]
I solved the problem.  Turns out that the problem was the command swig_import_helper().  swig was not setup in the path.  Would have been nice if it complained "I dont know what swig_import_helper() is" instead of complaining about _SoapySDR, but that is the solution for this issue
