### ISSUE TITLE
SoapySDR not found

### ISSUE THREAD

**Issue by nlbutts** [myriadrf/pyLMS7002Soapy#6]
I installed the library, but when I try and run measureSNA.py I get the following error message:

(base) C:\projects\pyLMS7002Soapy\examples>python measureSNA.py
Traceback (most recent call last):
  File "measureSNA.py", line 4, in <module>
    from pyLMS7002Soapy import pyLMS7002Soapy as pyLMSS
  File "C:\Users\Nick Butts\Anaconda3\lib\site-packages\pylms7002soapy-1.1.0-py3.7.egg\pyLMS7002Soapy\pyLMS7002Soapy.py", line 1, in <module>
    import SoapySDR
ModuleNotFoundError: No module named 'SoapySDR'

PothosFlow works fine and sees my Lime SDR. Any ideas?

**Comment by nlbutts** [comment]
I re-built the Lime code, then Soapy in Linux. I can't get this to work in Windows. On my LimeSDR is errors out frequently:
[ERROR] ERROR BEGIN DATA READING LIBUSB_ERROR_NO_DEVICE

**Comment by ldartez** [comment]
*bump*

**Comment by linuxguy123** [comment]
I've got the same problem with GnuRadio on Fedora 32 after having built LimeSuit and gr-limesdr from github source.  

I am not using Soapy. Do I need to ?

Are you able to run $LimeUtil without an error ?

**Comment by WilfredoLora** [comment]
@linuxguy123 In Linux, this is the order of how to install Soapy and Lime.

-SoapySDR
-LimeSuite #it will install and compile the soapy bindings if building from source.
-GNURadio
-gr-limesdr
